version: '3'

services:
  app:
    build: .
    container_name: kanban-app
    environment:
      FLASK_APP: kanban
      FLASK_ENV: development
    ports:
      - "5050:5050"
    volumes:
      - ".:/kanban"
    depends_on:
      - kanban-db
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
      - --port=5050

  kanban-db:
    image: postgres
    container_name: kanban-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: kanban-db
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - kanban-db
    ports:
      - "8081:8081"

volumes:
  postgres:
